---
title: "9.Bulk SC Comparison"
author: "Lindsay Hayes"
format: html
editor: source
editor_options: 
  chunk_output_type: console
---

```{r, load packages, echo=FALSE, message=FALSE}
library(tidyverse)
library(Seurat)
library(cowplot)
library(DESeq2)
```

```{r}
# Load SC Data
load("~/Desktop/4.Seurat/data/7.Myeloid_tidy.rda")
load("~/Desktop/4.Seurat/data/8.Tcell.rda")
load("~/Desktop/4.Seurat/data/full_dds.rda")
Myeloid
Tcell
dds

# Load bulk data
Mye_CSF <- read.csv(file = "writes/CSFvPBMCinMye.csv")
Lym_CSF <- read.csv(file = "writes/CSFvPBMCinLym.csv")
```

# Myeloid SC
```{r}
Mye_CSF |> filter(padj < 0.05 & log2FoldChange > 0) -> Bulk_Myeloid_CSF_enriched
# 3492 myeloid genes enriched in CSF
# 3054 of those in single cell dataset

Join_Myeloid <- JoinLayers(Myeloid)
common <- rownames(Join_Myeloid)[which(rownames(Join_Myeloid) %in% Bulk_Myeloid_CSF_enriched$gene)]
length(unique(common))

Idents(Join_Myeloid) <- Join_Myeloid$QC
a <- DotPlot(Join_Myeloid, features = common)
sc_common <- a$data

colnames(sc_common)[3] <- "gene"

#3054 genes
p1 <- ggplot(sc_common, aes(x = pct.exp, y = avg.exp)) + geom_point()
p2 <- ggplot(sc_common, aes(x = pct.exp, y = avg.exp.scaled)) + geom_point()
p3 <- ggplot(sc_common, aes(x = pct.exp, y = avg.exp)) + geom_point() + ylim(0,5)
p4 <- ggplot(sc_common, aes(x = pct.exp, y = avg.exp.scaled)) + geom_point() + ylim(0,1)
plot_grid(p1, p2, p3, p4)

ggsave(filename = "plots/4.myeloid/bulk-SC.svg", width = 6, height = 6)
```

```{r}
# test that sc_common is the same as pseudobulk
PBE <- PseudobulkExpression(Join_Myeloid, features = common, group.by = "QC")
all.equal(as.character(sc_common$gene), rownames(PBE$RNA))
plot(PBE$RNA, sc_common$avg.exp)
```


# Myeloid Bulk
```{r}
# Calculate bulk normalized counts for CSF_Myel samples
Myel_CSF_bulk <- dds[,which(dds$group == "CSF_Myel")]
Myel_CSF_bulk <- estimateSizeFactors(Myel_CSF_bulk)
normalized_bulk_counts <- counts(Myel_CSF_bulk, normalized=TRUE)

bulk.avg.exp <- as.data.frame(rowMeans(normalized_bulk_counts)) # dataframe of normalized counts
bulk.avg.exp$gene <- rowData(Myel_CSF_bulk)$gene_name


# COMBINE SC & BULK expression & Bulk CSF enrichment stats

tmp <- merge(sc_common, bulk.avg.exp, by = "gene")
colnames(tmp)[6] <- "bulk.avg.exp"
tmp <- tmp[-2321, ]

combined <- merge(tmp, Mye_CSF, by = "gene")


ggplot(combined, aes(x = bulk.avg.exp, y =avg.exp, color = pct.exp)) + geom_point() +
  theme_cowplot() + labs(subtitle = "3055 CSF enriched genes", x = "normalized bulk expr", y = "avg sc expr") + 
  scale_color_gradient(
    name = "% expr",
    limits = c(0, 100),
    low = "grey90",
    high = "black")

ggsave(filename = "plots/4.myeloid/bulk-SC_expr_v1.svg", width = 4, height = 4)

ggplot(combined, aes(x = log2(bulk.avg.exp), y =log2(avg.exp+1), color = pct.exp)) + geom_point() +
  theme_cowplot() + labs(subtitle = "3055 CSF enriched genes", x = "log2 normalized bulk expr", y = "log2 avg sc expr") + 
  scale_color_gradient(
    name = "% expr",
    limits = c(0, 100),
    low = "grey90",
    high = "black")
ggsave(filename = "plots/4.myeloid/bulk-SC_expr_v2.svg", width = 4, height = 4)

# binned data

combined <- combined %>%
  mutate(log_bulk = log2(bulk.avg.exp),
         bulk_bin = cut( log_bulk,
      breaks = seq(0, 20, by = 2),
      include.lowest = TRUE,
      right = FALSE))


ggplot(combined, aes(x = bulk_bin, y = log2(avg.exp+1))) + geom_boxplot(outlier.shape = NA) + theme_cowplot()
table(combined$bulk_bin)

ggsave(filename = "plots/4.myeloid/bulk-SC_boxplots.svg", width = 4, height = 4)
```

# Myeloid Heatmap
```{r}

combined |> filter(log2FoldChange > 5 & log_bulk > 10 & pct.exp > 10) |>
  select(gene) -> GOI

GOI <- as.character(GOI$gene)
order <- c(1,3,7,8,9,28,19,21,22,34,36,37,41,43, 
          10,27,18,11,13,15,16,20,23,24,30,31,32,38,39,40,25,12, 
           17,4,2,5,6,26,29,33,34,42,44, 14)

GOI_reordered <- GOI[order]

Join_Myeloid <- ScaleData(Join_Myeloid, features = GOI_reordered)
DoHeatmap(Join_Myeloid, feature = GOI_reordered, group.by = "seurat_clusters", group.colors = c("navy", "cornflowerblue","lightsteelblue1","blue")) + scale_fill_gradientn(colors = c("white", "white", "black"))
ggsave(filename = "plots/4.myeloid/SC_expr_topBulk_heatmap.svg", width = 5, height = 8)

```

# Myeloid Vlns
```{r}

VlnPlot(Myeloid, features = c("A2M", "SLC2A5", "LYVE1", "MSMO1"), cols = c("navy", "cornflowerblue","lightsteelblue1","blue"), ncol = 2)
ggsave(filename = "plots/4.myeloid/example_Vln.svg", width = 4, height = 5)

```



# T CELL
# TCell SC
```{r}
Lym_CSF |> filter(padj < 0.05 & log2FoldChange > 0) -> Bulk_Lymphoid_CSF_enriched
# 1072 myeloid genes enriched in CSF
# 1010 of those in single cell dataset

Join_Tcell <- JoinLayers(Tcell)
common <- rownames(Join_Tcell)[which(rownames(Join_Tcell) %in% Bulk_Lymphoid_CSF_enriched$gene)]
length(unique(common))

Idents(Join_Tcell) <- Join_Tcell$QC
a <- DotPlot(Join_Tcell, features = common)
sc_common <- a$data

colnames(sc_common)[3] <- "gene"

#1010 genes
p1 <- ggplot(sc_common, aes(x = pct.exp, y = avg.exp)) + geom_point()
p2 <- ggplot(sc_common, aes(x = pct.exp, y = avg.exp.scaled)) + geom_point()
p3 <- ggplot(sc_common, aes(x = pct.exp, y = avg.exp)) + geom_point() + ylim(0,5)
p4 <- ggplot(sc_common, aes(x = pct.exp, y = avg.exp.scaled)) + geom_point() + ylim(0,1)
plot_grid(p1, p2, p3, p4)
ggsave(filename = "plots/5.Tcell/bulk-SC.svg", width = 6, height = 6)
```

```{r}
# test that sc_common is the same as pseudobulk
PBE <- PseudobulkExpression(Join_Tcell, features = common, group.by = "QC")
all.equal(as.character(sc_common$gene), rownames(PBE$RNA))
plot(PBE$RNA, sc_common$avg.exp)
```



# Tcell Bulk
```{r}
# Calculate bulk normalized counts for CSF_Lym samples
T_CSF_bulk <- dds[,which(dds$group == "CSF_Lym")]
T_CSF_bulk <- estimateSizeFactors(T_CSF_bulk)
normalized_bulk_counts <- counts(T_CSF_bulk, normalized=TRUE)

bulk.avg.exp <- as.data.frame(rowMeans(normalized_bulk_counts)) # dataframe of normalized counts

bulk.avg.exp$gene <- rowData(T_CSF_bulk)$gene_name


# COMBINE SC & BULK & Bulk CSF enrichment stats
tmp <- merge(sc_common, bulk.avg.exp, by = "gene")
colnames(tmp)[6] <- "bulk.avg.exp"

tmp <- tmp[-765, ] # remove duplicate gene name

combined <- merge(tmp, Lym_CSF, by = "gene") # 1010

ggplot(combined, aes(x = bulk.avg.exp, y =avg.exp, color = pct.exp)) + geom_point() +
  theme_cowplot() + labs(subtitle = "1011 CSF enriched genes", x = "normalized bulk expr", y = "avg sc expr") + 
  scale_color_gradient(
    name = "% expr",
    limits = c(0, 100),
    low = "grey90",
    high = "black")

ggsave(filename = "plots/5.Tcell//bulk-SC_expr_v1.svg", width = 4, height = 4)

ggplot(combined, aes(x = log2(bulk.avg.exp), y =log2(avg.exp+1), color = pct.exp)) + geom_point() +
  theme_cowplot() + labs(subtitle = "1011 CSF enriched genes", x = "log2 normalized bulk expr", y = "log2 avg sc expr") + 
  scale_color_gradient(
    name = "% expr",
    limits = c(0, 100),
    low = "grey90",
    high = "black")

ggsave(filename = "plots/5.Tcell/bulk-SC_expr_v2.svg", width = 4, height = 4)

# binned data

combined <- combined |>
  mutate(log_bulk = log2(bulk.avg.exp),
         bulk_bin = cut( log_bulk,
      breaks = seq(0, 20, by = 2),
      include.lowest = TRUE,
      right = FALSE))


ggplot(combined, aes(x = bulk_bin, y = log2(avg.exp+1))) + geom_boxplot(outlier.shape = NA) + theme_cowplot()
ggsave(filename = "plots/5.Tcell/bulk-SC_boxplots.svg", width = 4, height = 4)
table(combined$bulk_bin)

```


# gene selection for heatmap
genes with high fold changes (enrichment in CSF) have no expression in single cell. pick the highest fold changes that have reasonable expression in sc.
```{r}

ggplot(combined, aes(y = log2FoldChange, x = pct.exp, color =log_bulk )) + geom_point() + theme_cowplot() + 
  scale_fill_gradientn(colors = c("white", "white", "black")) + geom_hline(yintercept =1) + geom_vline(xintercept = 10)


```




# T cell Heatmap
```{r}
Idents(Tcell) <- Tcell$cell_types

#  genes with greater CSF enrighment are poorly expressed in the single cell data
combined |> filter(log2FoldChange > 3) |>
  select(gene) -> GOI

GOI <- as.character(GOI$gene)

Tcell <- ScaleData(Tcell, features = GOI)
DoHeatmap(Tcell, feature = GOI, raster = T) + scale_fill_gradientn(colors = c("white", "white", "black"))
ggsave(filename = "plots/5.Tcell/heatmap_bulk-SC_sparse.svg", width = 6, height = 6)


#  genes with higher single cell expression are enriched in CSF but not as high a fold change
combined |> filter(log2FoldChange > 1 & pct.exp > 20) |>
  select(gene) -> GOI

GOI <- as.character(GOI$gene)

Tcell <- ScaleData(Tcell, features = GOI)
DoHeatmap(Tcell, feature = GOI, raster = T) + scale_fill_gradientn(colors = c("white", "white", "black"))
ggsave(filename = "plots/5.Tcell/heatmap_bulk-SC_full.svg", width = 6, height = 6)



```


# Tcell Vlns
```{r}
Idents(Tcell) <- Tcell$cell_types

VlnPlot(Tcell, features = c("MSMO1", "CCR5", "DPP4", "GIMAP5"), pt.size = 0, cols = c("darkgreen", "springgreen","gold","goldenrod","red","purple","grey"),ncol=2)
ggsave(filename = "plots/5.Tcell/example_Vln_Tcell.svg", width = 5, height = 5)

```


```{r}
sessionInfo()
```
