---
title: "8.Tcell Subclustering"
author: "Lindsay Hayes"
format: html
editor: source
editor_options: 
  chunk_output_type: console
---

# Subcluster T-cells and annotate
```{r, load packages, echo=FALSE, message=FALSE}
library(Seurat)
library(ggplot2)
library(cowplot)
library(readr)
library(readxl)
library(dplyr)

load("~/Desktop/4.Seurat/data/6.annotated.rda")
FinalFilter
```


# Tidy for cleaner clustering and markers
```{r, tidy}
`%notin%` <- Negate(`%in%`)
H1 <- rownames(FinalFilter)[(grep("^HBB", rownames(FinalFilter)))]
H2 <- rownames(FinalFilter)[(grep("^HBA", rownames(FinalFilter)))]
L <- rownames(FinalFilter)[(grepl("RPL", rownames(FinalFilter)))]
S <- rownames(FinalFilter)[(grepl("RPS", rownames(FinalFilter)))]
M <- rownames(FinalFilter)[(grepl("MT-", rownames(FinalFilter)))]
remove <- c(H1,H2,L,S, M)
TidyDat <- FinalFilter[rownames(FinalFilter) %notin% remove, ]
dim(FinalFilter)
dim(TidyDat)
rm(H1,H2,L,M,S,remove)
```

# Subset T-cells, recluster, and normalize
```{r, subset, message=FALSE, warning=FALSE}

Tcell <- subset(TidyDat, cell_types=="CD4" | cell_types== "CD8")
Tcell$cell_types <- droplevels(Tcell$cell_types)

DefaultAssay(Tcell) <- "RNA"
Tcell <- FindVariableFeatures(Tcell)
Tcell <- RunPCA(Tcell)
Tcell <- RunUMAP(Tcell, reduction = "pca", dims=1:50, seed.use = 502)
Tcell <- FindNeighbors(Tcell, reduction = "pca", dims = 1:50)
Tcell <- FindClusters(Tcell, resolution = 1)
table(Idents(Tcell))

DimPlot(Tcell, reduction = "umap", label = TRUE)
ggsave("plots/5.Tcell/umap_15.svg", width = 6, height = 5)

```

# Annotation with assistance of azimuth
```{r}
FeaturePlot(Tcell, features = c("FOXP3", "CD4", "CD8A", "TOP2A"),  reduction = "umap", order = T)
ggsave("plots/5.Tcell/umap_annotation1.svg", width = 6, height = 5)


# Annotation with Azimuth

tmp <- JoinLayers(Tcell)
counts <- tmp@assays$RNA$counts
saveRDS(counts, file = "data/TcellCounts.rds")
pred <- read_tsv("plots/5.Tcell/azimuth_pred.tsv")
rm(tmp, counts)

all.equal(rownames(Tcell@meta.data), pred$cell)
Tcell$pred <- pred$predicted.celltype.l2

DimPlot(Tcell, reduction = "umap", label = TRUE, group.by = "pred")
ggsave("plots/5.Tcell/umap_predictions.svg", width = 6, height = 5)
DimPlot(Tcell, reduction = "umap", label = TRUE)

table(Tcell$pred, Tcell$seurat_clusters)

# annotate clusters
Tcell$cell_types <- NA

Tcell$cell_types[which(Tcell$seurat_clusters == 0)] <-  "CD8-TEM"
Tcell$cell_types[which(Tcell$seurat_clusters == 1)] <-  "CD4-TCM"
Tcell$cell_types[which(Tcell$seurat_clusters == 2)] <-  "CD4-TCM"
Tcell$cell_types[which(Tcell$seurat_clusters == 3)] <-  "CD8-TEM"
Tcell$cell_types[which(Tcell$seurat_clusters == 4)] <-  "CD4-TEM"
Tcell$cell_types[which(Tcell$seurat_clusters == 5 & Tcell$pred == "CD8 TEM")] <- "CD8-TEM"
Tcell$cell_types[which(Tcell$seurat_clusters == 5 & Tcell$pred != "CD8 TEM")] <- "CD8-TCM"
Tcell$cell_types[which(Tcell$seurat_clusters == 6)] <-  "CD4-TCM"
Tcell$cell_types[which(Tcell$seurat_clusters == 7)] <-  "CD8-TEM"
Tcell$cell_types[Tcell$seurat_clusters %in% c(8)] <- "CD4-TCM"
Tcell$cell_types[Tcell$seurat_clusters %in% c(9)] <- "CD4-TCM"
Tcell$cell_types[Tcell$seurat_clusters %in% c(10)] <- "CD8-TEM"
Tcell$cell_types[Tcell$seurat_clusters %in% c(11)] <- "MAIT"
Tcell$cell_types[Tcell$seurat_clusters %in% c(12)] <- "CD8-TEM"
Tcell$cell_types[Tcell$seurat_clusters %in% c(13)] <- "Treg"
Tcell$cell_types[Tcell$seurat_clusters %in% c(14)] <- "prolif"

table(Tcell$pred, Tcell$cell_types)


Tcell$cell_types <- factor(Tcell$cell_types, levels = c("CD4-TCM", "CD4-TEM", "CD8-TCM", "CD8-TEM", "Treg", "MAIT", "prolif"))

DimPlot(Tcell, reduction = "umap", label = TRUE, group.by = "cell_types",
        cols = c("darkgreen", "green", "gold","goldenrod3", "red", "purple", "magenta"))

ggsave("plots/5.Tcell/umap_annotation.svg", width = 6, height = 5)
```


# Cluster Abundunce across samples
```{r, abundance}
table(Tcell$cell_types, Tcell$ID)

tmp <-table(Tcell$cell_types, Tcell$ID)
round(prop.table(tmp, margin = 2)*100,1)
abundance <- as.data.frame(round(prop.table(tmp, margin = 2)*100,1))
colnames(abundance) <- c("cluster", "ID", "Freq")

ggplot(abundance, aes(fill=cluster, y=Freq, x=ID)) + 
  geom_bar(position="stack", stat="identity") + theme_cowplot() +
  scale_fill_manual(values = c("darkgreen", "green", "gold","goldenrod3", "red", "purple", "magenta"))

ggsave("plots/5.Tcell/Tcell_abundance.svg", width = 6, height = 5)
```


# Markers & Heatmap

```{r, cluster markers}
Join_Tcell <- JoinLayers(Tcell)
Idents(Join_Tcell) <- Tcell$cell_types
table(Idents(Join_Tcell))
cluster_markers1 <- FindAllMarkers(Join_Tcell,
                                  logfc.threshold = 0.5,
                                  test.use = "roc",
                                  min.pct = 0.25,
                                  only.pos = TRUE)
table(cluster_markers1$cluster, dnn = "roc")
write.csv(cluster_markers1, file = "plots/5.Tcell/Tcell_cluster_markers_roc.csv")

Tcell$subtypes <- NA
Tcell$subtypes <- as.character(Tcell$cell_types)
Tcell$subtypes[Tcell$cell_types %in% c("CD4-TCM", "CD4-TEM")] <- "CD4"
Tcell$subtypes[Tcell$cell_types %in% c("CD8-TCM", "CD8-TEM")] <- "CD8"
table(Tcell$subtypes)

Join_Tcell <- JoinLayers(Tcell)
Idents(Join_Tcell) <- Tcell$subtypes
table(Idents(Join_Tcell))
cluster_markers2 <- FindAllMarkers(Join_Tcell,
                                  logfc.threshold = 0.5,
                                  test.use = "roc",
                                  min.pct = 0.25,
                                  only.pos = TRUE)
table(cluster_markers2$cluster, dnn = "roc")
write.csv(cluster_markers2, file = "plots/5.Tcell/Tcell_subtype_markers_roc.csv")

```
```{r, T cell heatmap, fig.height=10}
# heatmap
heatmap <- read_excel("plots/5.Tcell/Tcell_cluster_markers_roc.xlsx")

GOI <- heatmap |> filter(top == "top") |> distinct(gene) |> pull(gene)

Idents(Tcell) <- Tcell$cell_types
DotPlot(Tcell, features = rev(GOI), scale = T) + coord_flip() +
  scale_color_gradient2(
  low = "white",    
  mid = "grey80",     
  high = "darkgreen",    
  midpoint = 0)
ggsave("plots/5.Tcell/Tcell_heatmap.svg", width = 6, height = 10)
```


```{r}
save(Tcell, file = "data/8.Tcell.rda")

sessionInfo()
```